name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Restore Cached Gradle packages
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-primes
      # Runs a single command using the runners shell
      - name: Add local.properties
        env: # Or as an environment variable
          LOCALPROPS: ${{ secrets.LOCALPROPS }}
        run: echo $LOCALPROPS | base64 --decode > local.properties

      # Runs a set of commands using the runners shell
      - name: Chmod permissions
        run: sudo chmod +x ./gradlew
      # Runs a set of commands using the runners shell
      - name: Build
        run: ./gradlew clean build -x test

      - name: Cache Gradle packages
        id: cache-primes-save
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}